apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-picker-web-deployment
  namespace: stockapp
  labels:
    app: stockapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockapp-pickerweb
  template:
    metadata:
      labels:
        app: stockapp-pickerweb
    spec:
      containers:
        - name: main
          image: xximjasonxx/stock-picker-api:v1
          imagePullPolicy: Always
          env:
            - name: RedisServerHostname
              value: localhost
            - name: StockDataApiUrl
              value: http://stock-data-api-service.stockapp.svc.cluster.local
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: stock-data-api-service
  namespace: stockapp
  labels:
    app: stockapp

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stockapp-dataapi