apiVersion: v1
kind: Secret
metadata:
  name: sec-apikey
type: Opaque
data:
  apiKey: {{ .Values.data_api.apiKey | b64enc }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-data-api-deployment
  namespace: stockapp
  labels:
    app: stockapp

spec:
  replicas: {{ .Values.data_api.replicas }}
  selector:
    matchLabels:
      app: stockapp-dataapi
  template:
    metadata:
      labels:
        app: stockapp-dataapi
    spec:
      containers:
        - name: main
          image: xximjasonxx/stock-data-api:{{ .Values.data_api.imageTag }}
          imagePullPolicy: Always
          env:
            - name: ApiBaseUrl
              value: https://api.polygon.io
            - name: ApiKey
              valueFrom:
                secretKeyRef:
                  name: sec-apikey
                  key: apiKey
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: stock-data-api-service
  namespace: stockapp
  labels:
    app: stockapp

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stockapp-dataapi