#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: data-worker-cron-job#

#spec:
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#            - name: main-container
#              image: xximjasonxx/data-worker:v15
#              imagePullPolicy: Always
#          restartPolicy: OnFailure
#  schedule: "*/5 * * * *"

apiVersion: batch/v1
kind: Job
meata:
  name: data-worker-job

spec:
  template:
    spec:
      containers:
        - name: main-container
          image: xximjasonxx/data-worker:v15
          imagePullPolicy: Always
          env:
            - name: KafkaHost
              valueFrom:
                configMapKeyRef:
                  name: cm-kafkaconfig
                  key: KafkaHost
            - name: ApiBaseUrl
              valueFrom:
                configMapKeyRef:
                  name: cm-polygonconfig
                  key: ApiBaseUrl
            - name: ApiKey
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: sec-apikey
      restartPolicy: OnFailure