apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-update-consumer

  template:
    metadata:
        labels:
          app: price-update-consumer

    spec:
      containers:
        - name: main
          image: xximjasonxx/price-update-consumer:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: KafkaHost
              valueFrom:
                configMapKeyRef:
                  name: price-chance-consumer-config
                  key: kafkaHost
            - name: CosmosEndpointUri
              valueFrom:
                configMapKeyRef:
                  name: price-chance-consumer-config
                  key: cosmosEndpointUri
            - name: CosmosDatabaseName
              valueFrom:
                configMapKeyRef:
                  name: price-chance-consumer-config
                  key: cosmosDatabaseName
            - name: CosmosContainerName
              valueFrom:
                configMapKeyRef:
                  name: price-chance-consumer-config
                  key: cosmosContainerName
            - name: AccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.accessKey.secretName  }}
                  key: {{ .Values.env.accessKey.keyName }}
      restartPolicy: Always